### ISSUE TITLE
[REQ] Customize user agent

### ISSUE THREAD

**Issue by jimmy-lt** [Checkmarx/ast-github-action#148]
### Issue

The user agent is currently enforced to "_Github Action_" however, it can be useful to specify a different value. We hijack this feature to set the agent to the commit hash or the build ID. This way, users have got a quick knowledge from the Checkmarx One interface as to which commit generated the scan. 

### Proposed solution

Allow the `cx` CLI agent to be customized via an action input.

**Comment by pedrompflopes** [comment]
Hi @jimmy-lt  

Any specific reason to use the agent field ? We support scan tags, so it seems to be a perfect fit for your requirement. 

Thanks

**Comment by jimmy-lt** [comment]
Hi @pedrompflopes,

This is mainly because the "Scan Origin" information is everywhere within the CxOne interface so in a quick look we have the information of which part of the code we are talking about. Tags on the other way may require some additional clicks to get to the information.

In general knowing that the scan is coming from "Github Action" is not a useful information in our case. Commit hash or build ID provides a more direct feedback.

**Comment by pedrompflopes** [comment]
Hi @jimmy-lt 
We are currently using the agent field to collect metrics about the plugins, so that's the reason we don't allow it to be changed. 

We appreciate your support and opening the ticket but we suggest using the scan tags. We will release some improvement in UI in the near future that could help. 

Thanks.
